# Generated by Django 2.2.5 on 2020-01-17 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='attachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(blank=True, null=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=50)),
                ('Category_Created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_name', models.CharField(blank=True, max_length=15, null=True)),
                ('Client_email', models.EmailField(max_length=254)),
                ('Client_mobile_number', models.CharField(max_length=25)),
                ('Client_Create', models.DateTimeField(auto_now_add=True, null=True)),
                ('Client_Update', models.DateTimeField(auto_now=True)),
                ('Client_Firm_Registration_number', models.CharField(blank=True, max_length=15, null=True)),
                ('Client_Firm_Gst_number', models.CharField(blank=True, max_length=15, null=True)),
                ('Client_Firm_TIN_number', models.CharField(blank=True, max_length=15, null=True)),
                ('Client_PAN_number', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_email', models.EmailField(max_length=254)),
                ('Employee_Uniqe_id', models.CharField(blank=True, max_length=25, null=True)),
                ('Employee_otp', models.CharField(blank=True, max_length=15, null=True)),
                ('Employee_mobile_number', models.CharField(max_length=25)),
                ('Employee_DOB', models.DateField(blank=True, null=True)),
                ('Employee_DOJ', models.DateTimeField(blank=True, null=True)),
                ('Employee_Create', models.DateTimeField(auto_now_add=True, null=True)),
                ('Employee_Update', models.DateTimeField(auto_now=True)),
                ('IS_ACCOUNTENT', models.BooleanField(default=False)),
                ('Supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prodemoapp.Employee_data')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubCategory_name', models.CharField(max_length=50)),
                ('SubCategory_Created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prodemoapp.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_Title', models.CharField(max_length=50)),
                ('Task_Amount', models.CharField(blank=True, max_length=50, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('Task_Created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('Task_Comment', models.TextField(blank=True, null=True)),
                ('Task_Category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodemoapp.Category')),
                ('Task_Client_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Client_name_task', to='prodemoapp.Client')),
                ('Task_SubCategory_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodemoapp.SubCategory')),
                ('Task_assignment_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prodemoapp.Employee_data')),
                ('Task_attchments', models.ManyToManyField(blank=True, to='prodemoapp.attachments')),
            ],
        ),
        migrations.CreateModel(
            name='Organisations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Organisations_name', models.CharField(blank=True, max_length=25, null=True)),
                ('Organisations_email', models.EmailField(max_length=254)),
                ('Organisations_Uniqe_id', models.CharField(blank=True, max_length=25, null=True)),
                ('Organisationsp_no', models.CharField(max_length=25)),
                ('Organisations_Created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('which_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Organisations_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='employee_data',
            name='which_Organisations',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Employee_user', to='prodemoapp.Organisations'),
        ),
        migrations.AddField(
            model_name='employee_data',
            name='which_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Employee_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
