# Generated by Django 2.2.5 on 2020-01-17 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prodemoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_data',
            name='which_Organisations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Employee_user', to='prodemoapp.Organisations'),
        ),
    ]
