# Generated by Django 2.2.5 on 2020-01-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodemoapp', '0003_auto_20200117_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Task_Status',
            field=models.CharField(choices=[('1', 'New'), ('2', 'Pending'), ('3', 'In Progress'), ('4', 'Complete'), ('5', 'Cancle')], default='1', max_length=30),
        ),
    ]
