# Generated by Django 2.2.5 on 2020-01-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodemoapp', '0004_task_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Task_Status',
            field=models.CharField(choices=[('N', 'New'), ('P', 'Pending'), ('I', 'In Progress'), ('C', 'Complete'), ('Can', 'Cancle')], default='N', max_length=3),
        ),
    ]
