# Generated by Django 2.2.5 on 2020-01-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodemoapp', '0009_organisations_otp_forgot_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_data',
            name='Employee_Addres',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee_data',
            name='Employee_First_Name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='employee_data',
            name='Employee_Last_Name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='employee_data',
            name='Zip_Code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
