# Generated by Django 2.2.5 on 2020-01-27 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prodemoapp', '0011_auto_20200127_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_subscription_packages',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='buy_subscription_packages',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_By', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buy_subscription_packages',
            name='is_active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='buy_subscription_packages',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription_packages',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription_packages',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription_packages',
            name='is_active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='subscription_packages',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
