# Generated by Django 2.2.5 on 2020-01-30 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prodemoapp', '0013_auto_20200130_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages_type_Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Package_typs_name', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='packages',
            name='Package_Duration',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Half_yearly', 'Half_yearly'), ('Yearly', 'Yearly')], default='Monthly', max_length=30),
        ),
        migrations.AlterField(
            model_name='packages',
            name='Package_Type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prodemoapp.Packages_type_Choices'),
        ),
    ]
