# Generated by Django 2.2.5 on 2020-01-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodemoapp', '0014_auto_20200130_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Client_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
