# Generated by Django 2.2.5 on 2020-01-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodemoapp', '0015_auto_20200130_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='Client_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
