# Generated by Django 2.2.5 on 2020-01-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodemoapp', '0017_auto_20200130_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='Package_Duration',
            field=models.CharField(choices=[('Monthly', '30'), ('Quarterly', '90'), ('Half_yearly', '180'), ('Yearly', '365')], default='Monthly', max_length=30),
        ),
    ]
