# Generated by Django 2.2.5 on 2020-01-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodemoapp', '0018_auto_20200130_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='currency',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='Package_Type',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='Package_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
