# Generated by Django 2.2.5 on 2020-01-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodemoapp', '0019_auto_20200130_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='Package_Duration',
            field=models.CharField(choices=[('30', 'Monthly'), ('90', 'Quarterly'), ('180', 'Half_yearly'), ('365', 'Yearly')], default='Monthly', max_length=30),
        ),
    ]
