# Generated by Django 2.2.5 on 2020-01-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodemoapp', '0020_auto_20200130_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='Subscription_End_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='Subscription_start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
