# Generated by Django 2.2.5 on 2020-01-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodemoapp', '0021_auto_20200130_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisations',
            name='Logo_Image',
            field=models.ImageField(blank=True, null=True, upload_to='media/Logo_Image/'),
        ),
    ]
