# Generated by Django 2.2.5 on 2020-01-31 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodemoapp', '0025_auto_20200131_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Ordr_ID',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
