# Generated by Django 2.2.5 on 2020-01-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodemoapp', '0026_auto_20200131_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
