# Generated by Django 2.2.5 on 2020-02-01 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prodemoapp', '0027_auto_20200131_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='Subscription',
        ),
        migrations.AlterField(
            model_name='payment',
            name='Payment_Method',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='Payment_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prodemoapp.Payment'),
        ),
    ]
