# Generated by Django 2.2.5 on 2020-02-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodemoapp', '0030_auto_20200201_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='Subscription_days',
            new_name='Remaining_days',
        ),
        migrations.AlterField(
            model_name='payment',
            name='Ordr_ID',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Payment_Method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
