# Generated by Django 2.2.5 on 2020-02-01 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodemoapp', '0031_auto_20200201_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='Payment_status',
            new_name='Payment_ID',
        ),
    ]
