# Generated by Django 2.2.5 on 2020-02-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodemoapp', '0033_auto_20200201_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Ordr_ID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
