# Generated by Django 2.2.5 on 2020-02-03 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prodemoapp', '0036_task_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Task_assignment_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_of_task', to=settings.AUTH_USER_MODEL),
        ),
    ]
