# Generated by Django 2.2.5 on 2020-02-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodemoapp', '0037_auto_20200203_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Task_Status',
            field=models.CharField(choices=[('New', 'New'), ('Pending', 'Pending'), ('In_Progress', 'In Progress'), ('Complete', 'Complete'), ('Cancle', 'Cancle')], default='New', max_length=30),
        ),
    ]
