# Generated by Django 2.2.5 on 2020-02-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodemoapp', '0038_auto_20200203_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisations',
            name='createdBy',
        ),
        migrations.AlterField(
            model_name='organisations',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='Task_Status',
            field=models.CharField(choices=[('New', 'New'), ('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Complete', 'Complete'), ('Cancel', 'Cancel')], default='New', max_length=30),
        ),
    ]
