# Generated by Django 2.2.5 on 2020-02-06 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prodemoapp', '0039_auto_20200205_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='which_Organisations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prodemoapp.Organisations'),
        ),
        migrations.AddField(
            model_name='task',
            name='Due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Task_tracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_Status', models.CharField(choices=[('New', 'New'), ('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Complete', 'Complete'), ('InvoicePaid', 'InvoicePaid')], default='New', max_length=30)),
                ('date', models.DateField()),
                ('Task_Comment', models.TextField()),
                ('create_date', models.DateField()),
                ('Task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodemoapp.Task')),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
