# Generated by Django 2.2.5 on 2020-02-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodemoapp', '0041_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_tracking',
            name='Task_Comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task_tracking',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task_tracking',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
