# Generated by Django 2.2.5 on 2020-02-07 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prodemoapp', '0042_auto_20200206_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_data',
            name='Supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Supervisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='Task_Status',
            field=models.CharField(choices=[('New', 'New'), ('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Complete', 'Complete'), ('Cancel', 'Cancel'), ('InvoicePaid', 'InvoicePaid')], default='New', max_length=30),
        ),
    ]
