# Generated by Django 2.2.5 on 2020-02-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodemoapp', '0045_auto_20200212_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Category_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='SubCategory_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
