# Generated by Django 2.2.5 on 2020-02-13 13:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prodemoapp', '0046_auto_20200212_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='Task_assignment_to',
        ),
        migrations.AddField(
            model_name='task',
            name='Task_assignment_to',
            field=models.ManyToManyField(blank=True, null=True, related_name='assignment_of_task', to=settings.AUTH_USER_MODEL),
        ),
    ]
