# Generated by Django 2.2.5 on 2020-02-14 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodemoapp', '0047_auto_20200213_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='which_Organisations',
        ),
    ]
