# Generated by Django 2.2.5 on 2020-02-18 06:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodemoapp', '0048_remove_subcategory_which_organisations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Task_assignment_to',
            field=models.ManyToManyField(related_name='assignment_of_task', to=settings.AUTH_USER_MODEL),
        ),
    ]
