# Generated by Django 2.2.5 on 2020-02-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodemoapp', '0049_auto_20200218_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisations',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
