# Generated by Django 2.2.5 on 2020-02-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodemoapp', '0050_auto_20200218_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisations',
            name='Admin_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/Admin_img/'),
        ),
    ]
