# Generated by Django 2.2.5 on 2020-02-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodemoapp', '0053_organisations_is_mobile_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisations',
            name='is_subscribe',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
